### ISSUE TITLE
v1.7.0 fresh install not working

### ISSUE THREAD

**Issue by gabrielboliveira** [shprink/wordpress-hybrid-client#100]
I just forked the repo, and did a `git clone`, `git checkout v1.7.0`, `npm run installWPHC`, installed the WP REST API plugin at my blog, changed the `baseUrl` at config.json to point at my domain (the API was working), just as stated at the [Getting Started](http://wphc.julienrenaux.fr/getting-started.html) from your blog.

When I ran `npm run devserver`, it just shows me an error at Chrome Dev Tools console:
```
Uncaught Error: [$injector:modulerr] Failed to instantiate module wordpress-hybrid-client due to:
TypeError: $ionicNativeTransitionsProvider.setOptions is not a function
    at http://localhost:8080/bundle-da9c9e.js:112:43
    at Object.invoke (http://localhost:8080/bundle-da9c9e.js:13505:18)
    at runInvokeQueue (http://localhost:8080/bundle-da9c9e.js:13411:36)
    at http://localhost:8080/bundle-da9c9e.js:13420:12
    at forEach (http://localhost:8080/bundle-da9c9e.js:9391:21)
    at loadModules (http://localhost:8080/bundle-da9c9e.js:13401:6)
    at createInjector (http://localhost:8080/bundle-da9c9e.js:13327:12)
    at doBootstrap (http://localhost:8080/bundle-da9c9e.js:10685:21)
    at bootstrap (http://localhost:8080/bundle-da9c9e.js:10706:13)
    at angularInit (http://localhost:8080/bundle-da9c9e.js:10600:6)
```

`node -v = v4.2.1`
`npm -v = 3.3.9`

**Comment by shprink** [comment]
I figured, it is because of a dependency. Please use 1.7.1

https://github.com/shprink/wordpress-hybrid-client/tree/v1.7.1

Let me know so I can close this ticket

**Comment by gabrielboliveira** [comment]
@shprink Thanks! That fixed the problem.

**Comment by shprink** [comment]
Great!
