### ISSUE TITLE
Error Android build

### ISSUE THREAD

**Issue by taironebrito** [shprink/wordpress-hybrid-client#203]
Hello, how are you? Is appearing one error when I try to compile the application for android.
* Where:
Build file '/Users/taironebrito/Desktop/appp/platforms/android/build.gradle' line: 190

* What went wrong:
A problem occurred evaluating root project 'android'.
> Error: NDK integration is deprecated in the current plugin.  Consider trying the new experimental plugin.  For details, see http://tools.android.com/tech-docs/new-build-system/gradle-experimental.  Set "android.useDeprecatedNdk=true" in gradle.properties to continue using the current NDK integration.

Please help! :)

**Comment by taironebrito** [comment]
I have not found the gradle.properties, is The correct the project.properties ??

**Comment by taironebrito** [comment]
Please help :'(

**Comment by shprink** [comment]
Do you have any problem building another project?

Have you installed everything that's required by this project?

**Comment by taironebrito** [comment]
Thanks for the attention. I solved my problem with build, but i found another issue, i can’t configure 100% the Push notifications on Android.

Can you help me ?

Is not posting in the Plugin's Delight Studio users android, only the iPhone.

I follow all the steps.

Thanks!

**Comment by shprink** [comment]
IDK, you need to debug.

Have you set the senderID ?

**Comment by taironebrito** [comment]
I created Server API Key and Sender Id of the Cloud Messaging.
I downloaded the google-service.json and put it in the folder platforms/android.
I put the Server API Key in the Push Notification plugin in wordpress.

In which file I need to set the senderID?

Very Thanks!

**Comment by shprink** [comment]
https://github.com/shprink/wordpress-hybrid-client/blob/develop/PUSHNOTIFICATIONS.md#update-the-local-config

**Comment by taironebrito** [comment]
Thanks, Now I did all the steps correct, I can generate the apk. Do I install on my phone, but when I go to enable the option of Push he gets on the load infinite and not active.

**Comment by shprink** [comment]
check the console for errors

**Comment by taironebrito** [comment]
no error in terminal when i built the app :((

**Comment by shprink** [comment]
check the CONSOLE by debugging remotely on chrome

**Comment by taironebrito** [comment]
I have connected the phone in mode adb in the cannary, he identified it. Open the console and tried to activate the push. But nothing appears.

**Comment by shprink** [comment]
check the network tab

**Comment by taironebrito** [comment]
https://drive.google.com/file/d/0B0IqlPbr_pj0UzI1clhZcktJNG8/view?usp=sharing <https://drive.google.com/file/d/0B0IqlPbr_pj0UzI1clhZcktJNG8/view?usp=sharing>
this is my apk, please help!

**Comment by shprink** [comment]
Do not have time for that man. Please check the network tab. Check if the http requests are successful or not.

**Comment by taironebrito** [comment]
Ok, I'm sorry for this. It is because only lack this to finish the app and I am new in this area. I am learning.

When I open the app with the devtools from chrome, nothing appears. In any of the tabs.

**Comment by taironebrito** [comment]
In the ios version is working perfectly. Only in android it is giving this error.

**Comment by taironebrito** [comment]
I found the error.

04-04 13:34:46.777 18797-18797/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.google.android.gms.persistent, PID: 18797
                                                   Theme: themes:{}
                                                   java.lang.RuntimeException: Unable to create application com.google.android.gms.common.app.GmsApplication: java.lang.SecurityException: addOnPermissionsChangeListener: Neither user 10024 nor current process has android.permission.OBSERVE_GRANT_REVOKE_PERMISSIONS.
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4749)
                                                       at android.app.ActivityThread.-wrap1(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1424)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5456)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                    Caused by: java.lang.SecurityException: addOnPermissionsChangeListener: Neither user 10024 nor current process has android.permission.OBSERVE_GRANT_REVOKE_PERMISSIONS.
                                                       at android.os.Parcel.readException(Parcel.java:1620)
                                                       at android.os.Parcel.readException(Parcel.java:1573)
                                                       at android.content.pm.IPackageManager$Stub$Proxy.addOnPermissionsChangeListener(IPackageManager.java:5238)
                                                       at android.app.ApplicationPackageManager.addOnPermissionsChangeListener(ApplicationPackageManager.java:1138)
                                                       at com.google.android.gms.common.j.b.a(:com.google.android.gms:243)
                                                       at com.google.android.gms.common.app.GmsApplication.onCreate(:com.google.android.gms:218)
                                                       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4746)
                                                       at android.app.ActivityThread.-wrap1(ActivityThread.java) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1424) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:148) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5456) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
04-04 13:34:46.782 2333-2345/? W/ActivityManager: Process com.google.android.gms has crashed too many times: killing!
04-04 13:34:46.782 2333-2345/? I/ActivityManager: Killing 18797:com.google.android.gms.persistent/u0a24 (adj 0): crash

**Comment by taironebrito** [comment]
Good Night man, i found the correct error in chrome console, if you have a time please help me.

WARNING: Tried to load angular more than once.
cordova statusbar
cordova analytics
cordova globalization information
cordova network information
[pushNotifications]
[admob]
[admob] disabled
stateChangeSuccess Object Object Object Object
main controller
deviceready has not fired after 5 seconds.
nativepagetransitions is disabled or nativepagetransitions plugin is not present
wifi network information
[pushNotifications] init
ImgCache initialising
INFO: ImgCache initialising
[pushNotifications] hasPermission true
[pushNotifications] hasBeenUnregistered null
[pushNotifications] init Object Object
INFO: LocalFileSystem opened
INFO: Local cache folder opened: file:///storage/emulated/0/imgcache/
INFO: .nomedia file created.
ImgCache init: success!
Init: success!
reinit load false
wphcLoader attempt: 0
cordova socialsharing
INFO: File ea97b900b43f3f8fc5756a482fb3956f?s=96&d=mm&r=x loaded from cache
INFO: File a7a04ba94414c0dd1a1d3a5dc1d59c45?s=96&d=mm&r=x loaded from cache
INFO: File ce758d19406a4104dc3841b68ff1ef06?s=96&d=mm&r=x loaded from cache
INFO: File ea97b900b43f3f8fc5756a482fb3956f?s=96&d=mm&r=x loaded from cache
Error in Error callbackId: PushNotification1307871810 : TypeError: Cannot read property '$log' of undefined
Uncaught (in promise) TypeError: Cannot read property '$log' of undefined
    at file:///android_asset/www/bundle-0942d8.js:130631:22
    at PushNotification.emit (file:///android_asset/www/plugins/phonegap-plugin-push/www/push.js:193:38)
    at fail (file:///android_asset/www/plugins/phonegap-plugin-push/www/push.js:57:14)
    at Object.cordova.callbackFromNative (file:///android_asset/www/cordova.js:293:52)
    at processMessage (file:///android_asset/www/cordova.js:1079:17)
    at processMessages (file:///android_asset/www/cordova.js:1102:9)
stateChangeSuccess Object {url: "/params", class: "module-params", views: Object, name: "public.params"} Object {} Object {url: "/posts", class: "module-posts", views: Object, name: "public.posts"} Object {}
[pushNotifications] hasPermission true
stateChangeSuccess Object {url: "/pushNotifications", views: Object, name: "public.params.pushNotifications"} Object {} Object {url: "/params", class: "module-params", views: Object, name: "public.params"} Object {}
loading native show
loading native hide
loading native show
[pushNotifications] init Object {senderID: "892221558055"} Object {badge: true, sound: true, alert: true, clearBadge: true}
stateChangeSuccess Object {url: "/params", class: "module-params", views: Object, name: "public.params"} Object {} Object {url: "/pushNotifications", views: Object, name: "public.params.pushNotifications"} Object {}
[pushNotifications] hasPermission true
stateChangeSuccess Object {url: "/pushNotifications", views: Object, name: "public.params.pushNotifications"} Object {} Object {url: "/params", class: "module-params", views: Object, name: "public.params"} Object {}
loading native show
loading native hide
loading native show
[pushNotifications] init Object {senderID: "892221558055"} Object {badge: true, sound: true, alert: true, clearBadge: true}
Error in Error callbackId: PushNotification1307871848 : TypeError: Cannot read property '$log' of undefined
Uncaught TypeError: Cannot read property '$log' of undefined
Error in Error callbackId: PushNotification1307871855 : TypeError: Cannot read property '$log' of undefined
Uncaught TypeError: Cannot read property '$log' of undefined

Very very thanks!

**Comment by shprink** [comment]
I have tried your apk but it is not in debug mode. Please send me the debug mode apk so I can debug today.

**Comment by taironebrito** [comment]
https://drive.google.com/open?id=0B0IqlPbr_pj0NmIwaFJBUGtaVTg

THANKS SO MUCH!

**Comment by shprink** [comment]
Seriously dude... 

I do not get any json response from http://blogdagente.com.br/pnfw/register

It is written in the docs to test that url first => https://github.com/shprink/wordpress-hybrid-client/blob/develop/PUSHNOTIFICATIONS.md#update-the-local-config

You have a problem with your hosting. Check apache ou nginx setup to have access to pnfw plugin.

**Comment by shprink** [comment]
Otherwise your app looks good :)

**Comment by taironebrito** [comment]
Sorry my friend, it’s because my wordpress in maintenance mode. But   http://blogdagente.com.br/pnfw/register <http://blogdagente.com.br/pnfw/register> is working and return me for this {"error":"401","reason":"Unauthorized","detail":"Invalid HTTP method”}

I created one user for you.

login:shprink
pass:shprinkpassword

you can login in http://www.blogdagente.com.br/redacao <http://www.blogdagente.com.br/redacao>


Please take a look because here the app doesn’t work for me and my friends.

**Comment by shprink** [comment]
http://blogdagente.com.br/pnfw/register is not accessible from your device, remove the maintenance mode

**Comment by taironebrito** [comment]
Removed, try now!

**Comment by shprink** [comment]
you have this error => https://github.com/shprink/wordpress-hybrid-client/blob/develop/PUSHNOTIFICATIONS.md#parameter-oauth_consumer_key-is-missing

**Comment by taironebrito** [comment]
But I I disabled OAuth and the error continues.

**Comment by taironebrito** [comment]
Only in android version.

**Comment by shprink** [comment]
I am registered. You can write me a big check => https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=PFP99GE9V56RS

**Comment by taironebrito** [comment]
Registered where? I’ll donate you if can you help with this issue.

**Comment by shprink** [comment]
lol go check your push notif plugin I am registered.

**Comment by taironebrito** [comment]
LOL, you edit the apk ? Because with me and my friends doesn’t work.

**Comment by shprink** [comment]
It does not work because you had a problem with your server. Now toggle the notification back and forth and it will work.

I received the push notif BTW! Now $$$$

**Comment by taironebrito** [comment]
How much do you wanna? I don’t have many money, i’m studying app mobiles. But I know that's your job.

**Comment by shprink** [comment]
1 million dollars!!! $$$ lol don't worry bro I am kidding with you :)

**Comment by taironebrito** [comment]
hahahaha OMG! Very thanks bro, you’re the best.
e how i can fixe the app ? please tell me *-*

**Comment by shprink** [comment]
> Now toggle the notification back and forth

**Comment by taironebrito** [comment]
desactive and active the push plugin?

**Comment by taironebrito** [comment]
but what’s problem with my server? I need fixe this.

Very thanks bro,I'm learning a lot from you,

**Comment by taironebrito** [comment]
Hello bro, how are you? I’m here again hehe

Last question, i promise.

Everything is working now, but when i send the app for apple store it is reject by getting a white screen when you use it in TestFlight.
In xcode when i building with my iPhone it’s working normal, but in TestFlight it’s not working.

Am I doing something wrong?


Very Thanks!

**Comment by taironebrito** [comment]
2016-04-09 17:01:36.044 Blog da Gente[12413:193709] ERROR: Plugin 'AppRate' not found, or is not a CDVPlugin. Check your plugin mapping in config.xml.
2016-04-09 17:01:36.049 Blog da Gente[12413:193709] ERROR: Plugin 'AppRate' not found, or is not a CDVPlugin. Check your plugin mapping in config.xml.
2016-04-09 17:01:36.050 Blog da Gente[12413:193709] ERROR: Plugin 'File' not found, or is not a CDVPlugin. Check your plugin mapping in config.xml.
2016-04-09 17:01:36.050 Blog da Gente[12413:193709] ERROR: Plugin 'Device' not found, or is not a CDVPlugin. Check your plugin mapping in config.xml.
2016-04-09 17:01:36.051 Blog da Gente[12413:193709] ERROR: Plugin 'NetworkStatus' not found, or is not a CDVPlugin. Check your plugin mapping in config.xml.


> Em 9 de abr de 2016, à(s) 12:43, Tairone Brito <tairone.brito@gmail.com> escreveu:
> 
> Hello bro, how are you? I’m here again hehe
> 
> Last question, i promise.
> 
> Everything is working now, but when i send the app for apple store it is reject by getting a white screen when you use it in TestFlight.
> In xcode when i building with my iPhone it’s working normal, but in TestFlight it’s not working.
> 
> Am I doing something wrong?
> 
> 
> Very Thanks!
>
