### ISSUE TITLE
NPM Run devserver

### ISSUE THREAD

**Issue by xvilo** [shprink/wordpress-hybrid-client#254]
Hi,

If I want to do a npm run devserver I get the following error:
```
$ npm run devserver

> wordpress-hybrid-client@2.0.0-beta10 devserver /Volumes/HDD/users/xvilo/project/oord
> webpack-dev-server --port 8080 --json --progress

  0% compileevents.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:8080
  at Object.exports._errnoException (util.js:870:11)
  at exports._exceptionWithHostPort (util.js:893:20)
  at Server._listen2 (net.js:1234:14)
  at listen (net.js:1270:10)
  at net.js:1379:9
  at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:64:16)
  at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:83:10)


npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "devserver"
npm ERR! node v4.4.6
npm ERR! npm  v2.15.5
npm ERR! code ELIFECYCLE
npm ERR! wordpress-hybrid-client@2.0.0-beta10 devserver: `webpack-dev-server --port 8080 --json --progress`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wordpress-hybrid-client@2.0.0-beta10 devserver script 'webpack-dev-server --port 8080 --json --progress'.
npm ERR! This is most likely a problem with the wordpress-hybrid-client package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --port 8080 --json --progress
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs wordpress-hybrid-client
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls wordpress-hybrid-client
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Volumes/HDD/users/xvilo/project/oord/npm-debug.log
```

What is exactly happening here? It worked from my other machine, but I can't use that since iOS10/MacOS 10.12 combo ;)

**Comment by xvilo** [comment]
Didn't read the error carefully enough! Changed to port to `8081` in `package.json` works great again!
