### ISSUE TITLE
Only loading

### ISSUE THREAD

**Issue by mayurss786** [shprink/wordpress-hybrid-client#295]
It works fine in browser but when I build for android it shows only loading n loading n loading

I am using v2.0.0-beta14 

Also please tell when the pull to refresh work properly, also maxAge not works while setting it to zero

**Comment by shprink** [comment]
please be more explicit on what is the error. Closing until you have at least error messages to share

**Comment by mayurss786** [comment]
here it is

TypeError: Object.assign is not a function
    at _default.getMergedQuery (file:///android_asset/www/bundle-bbfeaa.js:126058:28)
    at _default.doLoadMore (file:///android_asset/www/bundle-bbfeaa.js:126022:31)
    at _default.init (file:///android_asset/www/bundle-bbfeaa.js:125993:26)
    at fn (eval at <anonymous> (file:///android_asset/www/bundle-bbfeaa.js:27900:16), <anonymous>:2:252)
    at Controller.destination.(anonymous function) [as onLoad] (file:///android_asset/www/bundle-bbfeaa.js:23371:23)
    at Controller.load (file:///android_asset/www/bundle-bbfeaa.js:129301:24)
    at file:///android_asset/www/bundle-bbfeaa.js:129288:24
    at file:///android_asset/www/bundle-bbfeaa.js:32585:32
    at completeOutstandingRequest (file:///android_asset/www/bundle-bbfeaa.js:19456:11)
    at file:///android_asset/www/bundle-bbfeaa.js:19732:8(anonymous function) @ console-via-logger.js:174(anonymous function) @ bundle-bbfeaa.js:27056(anonymous function) @ bundle-bbfeaa.js:23769(anonymous function) @ bundle-bbfeaa.js:32588completeOutstandingRequest @ bundle-bbfeaa.js:19456(anonymous function) @ bundle-bbfeaa.js:19732

**Comment by shprink** [comment]
Ok sorry about that this has been fixed https://github.com/shprink/wordpress-hybrid-client/issues/294

Releasing a new version right now.

**Comment by shprink** [comment]
Done.

To upgrade checkout `git fetch --all && git checkout v2.0.0-beta15`

**Comment by mayurss786** [comment]
Great will try in morning

**Comment by mayurss786** [comment]
yeah now fixed
